name: Release

on:
  push:
    tags: ["[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]"]

jobs:

  build_release:

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          mkdir ~/bin
          make CitySim

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: release-files
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ~/bin/CitySim
            LICENSE.txt
